import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Lightbulb } from "lucide-react";

interface HealthTipsProps {
  onSelect: (prompt: string) => void;
  onClose: () => void;
}

const HealthTips = ({ onSelect, onClose }: HealthTipsProps) => {
  const handleGetTip = () => {
    onSelect("Give me a random, interesting health tip.");
  };

  return (
    <Card className="w-full text-center">
      <CardHeader>
        <CardTitle>AI-Powered Health Tips</CardTitle>
        <CardDescription>
          Click the button to get a unique health tip generated by our AI.
        </CardDescription>
      </CardHeader>
      <CardContent className="flex flex-col items-center justify-center p-8">
        <Lightbulb className="h-16 w-16 text-yellow-400 mb-6" />
        <Button 
          onClick={handleGetTip}
          className="bg-healthcare-primary hover:bg-healthcare-dark"
        >
          Get a Health Tip from AI
        </Button>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button variant="outline" onClick={onClose}>
          Close
        </Button>
      </CardFooter>
    </Card>
  );
};

export default HealthTips;
