// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omjvoyxraxzajvfjqrky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tanZveXhyYXh6YWp2Zmpxcmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTMzMzgsImV4cCI6MjA2MTUyOTMzOH0.ad9s3x5lTDSgqGd26ZlLbR1QIlkHcgQiwnotxlX7C7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);